---
references:
  - "File: /lib/ButtonToSwitch_ESP32/src/ButtonToSwitch_ESP32.h"
generationTime: 2026-06-01T14:47:04.203Z
---
classDiagram
    %% ===== STRUCTS/DATA TYPES =====
    class MpbOtpts_t {
        +bool isOn
        +bool isEnabled
        +bool pilotOn
        +bool wrnngOn
        +bool isVoided
        +bool isOnScndry
        +uint16_t otptCurVal
    }

    %% ===== INTERFACES/ABSTRACT BASES =====
    class PressSignalSource {
        <<interface>>
        -String name
        +getIsPressed() bool*
    }

    %% ===== BASE CLASS =====
    class DbncdMPBttn {
        <<Abstract>>
        #enum fdaDmpbStts
        #int8_t _mpbttnPin
        #bool _pulledUp
        #bool _typeNO
        #unsigned long int _dbncTimeOrigSett
        #bool _beginDisabled
        #static uint8_t _btsLastSerialNum
        #uint8_t _btsSerialNum
        #bool _isEnabled
        #volatile bool _isOn
        #bool _isOnDisabled
        #volatile bool _isPressed
        #fncVdPtrPrmPtrType _fnVdPtrPrmWhnTrnOff
        #fncVdPtrPrmPtrType _fnVdPtrPrmWhnTrnOn
        #fncPtrType _fnWhnTrnOff
        #fncPtrType _fnWhnTrnOn
        #TaskHandle_t _taskToNotifyHndl
        #TaskHandle_t _taskWhileOnHndl
        #SemaphoreHandle_t _isOnMutex
        #PressSignalSource* _signalSource
        +DbncdMPBttn()
        +DbncdMPBttn(int8_t, bool, bool, unsigned long int)
        +DbncdMPBttn(PressSignalSource*, unsigned long int)
        +~DbncdMPBttn()*
        +begin(unsigned long int) bool
        +clrStatus(bool) void
        +disable() void
        +enable() void
        +end() bool
        +getBtsSerialNum() uint8_t
        +getCurDbncTime() unsigned long int
        +getIsEnabled() bool
        +getIsOn() bool
        +getIsOnDisabled() bool
        +getOtptsSttsPkgd() uint32_t
        +getOutputsChange() bool
        +getTaskToNotify() TaskHandle_t
        +getTaskWhileOn() TaskHandle_t
        +pause() bool
        +resume() bool
        +setDbncTime(unsigned long int) bool
        +setFnWhnTrnOffPtr(fncPtrType) void
        +setFnWhnTrnOnPtr(fncPtrType) void
        +setFVPPWhnTrnOff(fncVdPtrPrmPtrType, void*) void
        +setFVPPWhnTrnOn(fncVdPtrPrmPtrType, void*) void
        +setIsOnDisabled(bool) void
        +setOutputsChange(bool) void
        +setTaskToNotify(TaskHandle_t) void
        +setTaskWhileOn(TaskHandle_t)* void
        #virtual updFdaState()*
    }

    %% ===== FIRST LEVEL INHERITANCE =====
    class DbncdDlydMPBttn {
        +DbncdDlydMPBttn()
        +DbncdDlydMPBttn(int8_t, bool, bool, unsigned long int, unsigned long int)
        +DbncdDlydMPBttn(PressSignalSource*, unsigned long int, unsigned long int)
        +~DbncdDlydMPBttn()*
        +setStrtDelay(unsigned long int) void
    }

    %% ===== LATCHED HIERARCHIES =====
    class LtchMPBttn {
        <<Abstract>>
        #enum fdaLmpbStts
        #bool _isLatched
        #bool _trnOffASAP
        #volatile bool _validUnlatchPend
        #volatile bool _validUnlatchRlsPend
        +LtchMPBttn()
        +LtchMPBttn(int8_t, bool, bool, unsigned long int, unsigned long int)
        +LtchMPBttn(PressSignalSource*, unsigned long int, unsigned long int)
        +~LtchMPBttn()*
        +begin(unsigned long int) bool
        +clrStatus(bool) void
        +getIsLatched() bool
        +getTrnOffASAP() bool
        +getUnlatchPend() bool
        +getUnlatchRlsPend() bool
        +setTrnOffASAP(bool) void
        +setUnlatchPend(bool) void
        +setUnlatchRlsPend(bool) void
        +unlatch() bool
        #virtual updValidUnlatchStatus()*
    }

    class TgglLtchMPBttn {
        <<Concrete>>
        +TgglLtchMPBttn()
        +TgglLtchMPBttn(int8_t, bool, bool, unsigned long int, unsigned long int)
        +TgglLtchMPBttn(PressSignalSource*, unsigned long int, unsigned long int)
        +~TgglLtchMPBttn()*
    }

    class TmLtchMPBttn {
        <<Concrete>>
        #bool _tmRstbl
        #unsigned long int _srvcTime
        #unsigned long int _srvcTimerStrt
        +TmLtchMPBttn()
        +TmLtchMPBttn(int8_t, unsigned long int, bool, bool, unsigned long int, unsigned long int)
        +TmLtchMPBttn(PressSignalSource*, unsigned long int, unsigned long int, unsigned long int)
        +~TmLtchMPBttn()*
        +clrStatus(bool) void
        +getSrvcTime() unsigned long int
        +setSrvcTime(unsigned long int) bool
        +setTmerRstbl(bool) void
    }

    class HntdTmLtchMPBttn {
        <<Concrete>>
        #unsigned long int _wrnngMs
        #unsigned int _wrnngPrctg
        #bool _keepPilot
        #volatile bool _pilotOn
        #volatile bool _wrnngOn
        #fncVdPtrPrmPtrType _fnVdPtrPrmWhnTrnOffPilot
        #fncVdPtrPrmPtrType _fnVdPtrPrmWhnTrnOnPilot
        #fncVdPtrPrmPtrType _fnVdPtrPrmWhnTrnOffWrnng
        #fncVdPtrPrmPtrType _fnVdPtrPrmWhnTrnOnWrnng
        +HntdTmLtchMPBttn()
        +HntdTmLtchMPBttn(int8_t, unsigned long int, unsigned int, bool, bool, unsigned long int, unsigned long int)
        +HntdTmLtchMPBttn(PressSignalSource*, unsigned long int, unsigned int, unsigned long int, unsigned long int)
        +~HntdTmLtchMPBttn()
        +begin(unsigned long int) bool
        +clrStatus(bool) void
        +getPilotOn() bool
        +getWrnngOn() bool
        +setKeepPilot(bool) void
        +setWrnngPrctg(unsigned int) bool
    }

    class XtrnUnltchMPBttn {
        <<Concrete>>
        #DbncdDlydMPBttn* _unLtchBttn
        #bool _xtrnUnltchPRlsCcl
        +XtrnUnltchMPBttn()
        +XtrnUnltchMPBttn(int8_t, DbncdDlydMPBttn*, bool, bool, unsigned long int, unsigned long int)
        +XtrnUnltchMPBttn(PressSignalSource*, DbncdDlydMPBttn*, unsigned long int, unsigned long int)
        +XtrnUnltchMPBttn(int8_t, bool, bool, unsigned long int, unsigned long int)
        +XtrnUnltchMPBttn(PressSignalSource*, unsigned long int, unsigned long int)
        +begin(unsigned long int) bool
        +clrStatus(bool) void
    }

    %% ===== DOUBLE ACTION HIERARCHIES =====
    class DblActnLtchMPBttn {
        <<Abstract>>
        #enum fdaDALmpbStts
        #volatile bool _isOnScndry
        #unsigned long _scndModActvDly
        #unsigned long _scndModTmrStrt
        #bool _validScndModPend
        #fncVdPtrPrmPtrType _fnVdPtrPrmWhnTrnOffScndry
        #fncVdPtrPrmPtrType _fnVdPtrPrmWhnTrnOnScndry
        #void (*_fnWhnTrnOffScndry)()
        #void (*_fnWhnTrnOnScndry)()
        #TaskHandle_t _taskWhileOnScndryHndl
        +DblActnLtchMPBttn()
        +DblActnLtchMPBttn(int8_t, bool, bool, unsigned long int, unsigned long int)
        +DblActnLtchMPBttn(PressSignalSource*, unsigned long int, unsigned long int)
        +~DblActnLtchMPBttn()
        +begin(unsigned long int) bool
        +clrStatus(bool) void
        +getFnWhnTrnOffScndry() fncPtrType
        +getFnWhnTrnOnScndry() fncPtrType
        +getFVPPWhnTrnOffScndry() fncVdPtrPrmPtrType
        +getFVPPWhnTrnOnScndry() fncVdPtrPrmPtrType
        +getIsOnScndry() bool
        +getScndModActvDly() unsigned long
        +getTaskWhileOnScndry() TaskHandle_t
        +setFnWhnTrnOffScndryPtr(void(*)()) void
        +setFnWhnTrnOnScndryPtr(void(*)()) void
        +setFVPPWhnTrnOffScndry(fncVdPtrPrmPtrType, void*) void
        +setFVPPWhnTrnOnScndry(fncVdPtrPrmPtrType, void*) void
        +setScndModActvDly(unsigned long) bool
        +setTaskWhileOnScndry(TaskHandle_t) void
        #virtual stOnScndMod_Do()*
    }

    class DDlydDALtchMPBttn {
        <<Concrete>>
        +DDlydDALtchMPBttn()
        +DDlydDALtchMPBttn(int8_t, bool, bool, unsigned long int, unsigned long int)
        +DDlydDALtchMPBttn(PressSignalSource*, unsigned long int, unsigned long int)
        +~DDlydDALtchMPBttn()
        +clrStatus(bool) void
    }

    class SldrDALtchMPBttn {
        <<Concrete>>
        #bool _autoSwpDirOnEnd
        #bool _autoSwpDirOnPrss
        #bool _curSldrDirUp
        #uint16_t _otptCurVal
        #bool _otptCurValIsMax
        #bool _otptCurValIsMin
        #unsigned long _otptSldrSpd
        #uint16_t _otptSldrStpSize
        #uint16_t _otptValMax
        #uint16_t _otptValMin
        +SldrDALtchMPBttn()
        +SldrDALtchMPBttn(int8_t, bool, bool, unsigned long int, unsigned long int, uint16_t)
        +~SldrDALtchMPBttn()
        +clrStatus(bool) void
        +getOtptCurVal() uint16_t
        +getOtptCurValIsMax() bool
        +getOtptCurValIsMin() bool
        +getOtptSldrSpd() unsigned long
        +getOtptSldrStpSize() uint16_t
        +getOtptValMax() uint16_t
        +getOtptValMin() uint16_t
        +getSldrDirUp() bool
        +setOtptCurVal(uint16_t) bool
        +setOtptSldrSpd(uint16_t) bool
        +setOtptSldrStpSize(uint16_t) bool
        +setOtptValMax(uint16_t) bool
        +setOtptValMin(uint16_t) bool
        +setSldrDirDn() bool
        +setSldrDirUp() bool
        +setSwpDirOnEnd(bool) void
        +setSwpDirOnPrss(bool) void
        +swapSldrDir() bool
    }

    %% ===== VOIDABLE HIERARCHIES =====
    class VdblMPBttn {
        <<Abstract>>
        #enum fdaVmpbStts
        #bool _isVoided
        #bool _frcdOtptLvlWhnVdd
        #bool _stOnWhnVddOtptLvlFrcd
        #bool _validVoidPend
        #bool _validUnvoidPend
        #fncVdPtrPrmPtrType _fnVdPtrPrmWhnTrnOffVdd
        #fncVdPtrPrmPtrType _fnVdPtrPrmWhnTrnOnVdd
        +VdblMPBttn()
        +VdblMPBttn(int8_t, bool, bool, unsigned long int, unsigned long int, bool)
        +~VdblMPBttn()*
        +clrStatus(bool) void
        +getFnWhnTrnOffVdd() fncPtrType
        +getFnWhnTrnOnVdd() fncPtrType
        +getFVPPWhnTrnOffVdd() fncVdPtrPrmPtrType
        +getFVPPWhnTrnOnVdd() fncVdPtrPrmPtrType
        +getIsVoided() bool
        +setFnWhnTrnOffVddPtr(void(*)()) void
        +setFnWhnTrnOnVddPtr(void(*)()) void
        +setFVPPWhnTrnOffVdd(fncVdPtrPrmPtrType, void*) void
        +setFVPPWhnTrnOnVdd(fncVdPtrPrmPtrType, void*) void
        +setIsNotVoided() bool
        +setIsVoided() bool
        #virtual updVoidStatus()*
    }

    class TmVdblMPBttn {
        <<Concrete>>
        #unsigned long int _voidTime
        #unsigned long int _voidTmrStrt
        +TmVdblMPBttn()
        +TmVdblMPBttn(int8_t, unsigned long int, bool, bool, unsigned long int, unsigned long int, bool)
        +~TmVdblMPBttn()*
        +begin(unsigned long int) bool
        +clrStatus() void
        +getVoidTime() unsigned long int
        +setVoidTime(unsigned long int) bool
    }

    class SnglSrvcVdblMPBttn {
        <<Concrete>>
        +SnglSrvcVdblMPBttn()
        +SnglSrvcVdblMPBttn(int8_t, bool, bool, unsigned long int, unsigned long int)
        +~SnglSrvcVdblMPBttn()*
        +begin(unsigned long int) bool
    }

    %% ===== RELATIONSHIPS =====
    DbncdMPBttn "1" o-- "1" PressSignalSource : uses
    DbncdMPBttn <|-- DbncdDlydMPBttn : inherits
    DbncdDlydMPBttn <|-- LtchMPBttn : inherits
    LtchMPBttn <|-- TgglLtchMPBttn : inherits
    LtchMPBttn <|-- TmLtchMPBttn : inherits
    TmLtchMPBttn <|-- HntdTmLtchMPBttn : inherits
    LtchMPBttn <|-- XtrnUnltchMPBttn : inherits
    XtrnUnltchMPBttn "1" o-- "1" DbncdDlydMPBttn : references
    LtchMPBttn <|-- DblActnLtchMPBttn : inherits
    DblActnLtchMPBttn <|-- DDlydDALtchMPBttn : inherits
    DblActnLtchMPBttn <|-- SldrDALtchMPBttn : inherits
    DbncdDlydMPBttn <|-- VdblMPBttn : inherits
    VdblMPBttn <|-- TmVdblMPBttn : inherits
    VdblMPBttn <|-- SnglSrvcVdblMPBttn : inherits